// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251030001103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Models.Alert", b =>
                {
                    b.Property<long>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AlertID"));

                    b.Property<bool>("Acknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DataID")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlertID");

                    b.HasIndex("DataID");

                    b.HasIndex("PatientID");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("WebApplication2.Models.ClinicianPatient", b =>
                {
                    b.Property<int>("ClinicianID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClinicianID", "PatientID");

                    b.HasIndex("PatientID");

                    b.ToTable("ClinicianPatients");
                });

            modelBuilder.Entity("WebApplication2.Models.Comment", b =>
                {
                    b.Property<long>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CommentID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DataID")
                        .HasColumnType("bigint");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentID");

                    b.HasIndex("DataID");

                    b.HasIndex("PatientID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebApplication2.Models.CommentReply", b =>
                {
                    b.Property<long>("ReplyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReplyID"));

                    b.Property<int>("ClinicianID")
                        .HasColumnType("int");

                    b.Property<long>("CommentID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReplyID");

                    b.HasIndex("ClinicianID");

                    b.HasIndex("CommentID");

                    b.ToTable("CommentReplies");
                });

            modelBuilder.Entity("WebApplication2.Models.FrameMetric", b =>
                {
                    b.Property<long>("MetricID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MetricID"));

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ContactAreaPct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("DataID")
                        .HasColumnType("bigint");

                    b.Property<int>("PeakPressure")
                        .HasColumnType("int");

                    b.HasKey("MetricID");

                    b.HasIndex("DataID")
                        .IsUnique();

                    b.ToTable("FrameMetrics");
                });

            modelBuilder.Entity("WebApplication2.Models.Log", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("UserID");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("WebApplication2.Models.SensorFrame", b =>
                {
                    b.Property<long>("DataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DataID"));

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PayloadCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("DataID");

                    b.HasIndex("PatientID", "Timestamp");

                    b.ToTable("SensorFrames");
                });

            modelBuilder.Entity("WebApplication2.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication2.Models.Alert", b =>
                {
                    b.HasOne("WebApplication2.Models.SensorFrame", "Data")
                        .WithMany()
                        .HasForeignKey("DataID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApplication2.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Data");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplication2.Models.ClinicianPatient", b =>
                {
                    b.HasOne("WebApplication2.Models.User", "Clinician")
                        .WithMany("ClinicianLinks")
                        .HasForeignKey("ClinicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication2.Models.User", "Patient")
                        .WithMany("PatientLinks")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplication2.Models.Comment", b =>
                {
                    b.HasOne("WebApplication2.Models.SensorFrame", "Data")
                        .WithMany()
                        .HasForeignKey("DataID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApplication2.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Data");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplication2.Models.CommentReply", b =>
                {
                    b.HasOne("WebApplication2.Models.User", "Clinician")
                        .WithMany()
                        .HasForeignKey("ClinicianID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApplication2.Models.Comment", "Comment")
                        .WithMany("Replies")
                        .HasForeignKey("CommentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("WebApplication2.Models.FrameMetric", b =>
                {
                    b.HasOne("WebApplication2.Models.SensorFrame", "Data")
                        .WithOne("Metric")
                        .HasForeignKey("WebApplication2.Models.FrameMetric", "DataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Data");
                });

            modelBuilder.Entity("WebApplication2.Models.Log", b =>
                {
                    b.HasOne("WebApplication2.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication2.Models.SensorFrame", b =>
                {
                    b.HasOne("WebApplication2.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebApplication2.Models.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("WebApplication2.Models.SensorFrame", b =>
                {
                    b.Navigation("Metric");
                });

            modelBuilder.Entity("WebApplication2.Models.User", b =>
                {
                    b.Navigation("ClinicianLinks");

                    b.Navigation("PatientLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
